platform: linux

image_resource:
  type: registry-image

inputs:
  - name: pxf_src
  - name: pxf_shipit_file
  - name: pxf_artifacts

outputs:
  - name: pxf_artifacts

params:
  ATC_EXTERNAL_URL:
  BUILD_PIPELINE_NAME:
  BUILD_JOB_NAME:
  BUILD_NAME:
  PXF_OSL_FILE_PREFIX:
  PXF_ODP_FILE_PREFIX:
  RELENG_DROP_URL:
  RELENG_OSL_DROP_URL:
  RELENG_ODP_DROP_URL:

run:
  path: pxf_src/concourse/scripts/generate_releng_email.bash
