platform: linux

image_resource:
  type: registry-image

inputs:
- name: pxf_src
- name: pxf_gp5_tarball_rhel7
- name: pxf_gp6_tarball_rhel7
- name: pxf_gp6_tarball_rhel8
- name: pxf_gp6_tarball_ubuntu18

params:
  GCS_RELEASES_BUCKET:
  GCS_RELEASES_PATH:
  GIT_BRANCH:
  GIT_EMAIL:
  GIT_REMOTE_URL:
  GIT_SSH_KEY:
  GIT_USERNAME:
  GOOGLE_CREDENTIALS:

run:
  path: pxf_src/concourse/scripts/promote_pxf_artifacts.bash
